#!/usr/bin/env bash
# Shared helpers for the local start scripts (run-full-stack, run-web, run-desktop).
# Usage: source "${ROOT}/scripts/stack-common.sh"
#
# Kept in one place so all three scripts free ports, wait for the backend, and
# rewrite runtime-config.js the same way. A divergence here would mean a
# "desktop" run silently behaved like a browser run.

RUNTIME_CONFIG_REL="src/assets/config/runtime-config.js"
RUNTIME_CONFIG_BACKUP=""

# ── Port handling ────────────────────────────────────────────────────────
# Stop whatever is already listening, so a script run does not fail on a stale
# dev server from a previous run.
free_listen_port() {
  local port="$1"
  local label="$2"
  local pids=""

  if command -v lsof >/dev/null 2>&1; then
    pids="$(lsof -t -iTCP:"${port}" -sTCP:LISTEN 2>/dev/null || true)"
  fi

  if [[ -n "${pids}" ]]; then
    echo "stopping ${label} on port ${port} (PIDs: ${pids//$'\n'/ })..."
    # shellcheck disable=SC2086
    kill ${pids} 2>/dev/null || true
    sleep 0.4
    pids="$(lsof -t -iTCP:"${port}" -sTCP:LISTEN 2>/dev/null || true)"
    if [[ -n "${pids}" ]]; then
      # shellcheck disable=SC2086
      kill -9 ${pids} 2>/dev/null || true
    fi
    return
  fi

  if command -v fuser >/dev/null 2>&1 && fuser "${port}/tcp" >/dev/null 2>&1; then
    echo "stopping ${label} on port ${port} (fuser)..."
    fuser -k "${port}/tcp" 2>/dev/null || true
    sleep 0.4
  fi
}

# ── Backend readiness ────────────────────────────────────────────────────
# A listening socket is not enough: the API answers /categories only once
# Sequelize has synced and the routes are mounted.
wait_for_backend_http() {
  local port="$1"
  local script_name="$2"
  local n=0
  local max="${3:-80}"
  while ((n < max)); do
    if curl -sf -o /dev/null "http://127.0.0.1:${port}/categories" 2>/dev/null; then
      echo "${script_name}: backend is listening on port ${port}"
      return 0
    fi
    sleep 0.25
    n=$((n + 1))
  done
  echo "${script_name}: timed out waiting for backend on port ${port}" >&2
  return 1
}

prepare_backend_deps() {
  local backend_dir="$1"
  local script_name="$2"
  if [[ ! -d "${backend_dir}/node_modules" ]]; then
    echo "${script_name}: installing backend dependencies in ${backend_dir}..."
    (cd "${backend_dir}" && npm install)
  fi
}

# ── Runtime configuration ────────────────────────────────────────────────
# This is the whole deployment-agnostic contract in one file: the bundle is
# identical in both modes, and only this override differs. Refuse to run if the
# tracked file has local edits, so a half-finished experiment is never
# silently reverted by the cleanup trap.
runtime_config_prepare() {
  local root="$1"
  local api_base_url="$2"
  local platform="$3"
  local script_name="$4"
  local abs="${root}/${RUNTIME_CONFIG_REL}"

  if [[ -n "$(git -C "${root}" status --porcelain -- "${RUNTIME_CONFIG_REL}" 2>/dev/null || true)" ]]; then
    echo "${script_name}: ${RUNTIME_CONFIG_REL} has uncommitted local changes." >&2
    echo "${script_name}: commit or stash them first; this script rewrites that file." >&2
    return 1
  fi

  RUNTIME_CONFIG_BACKUP="$(mktemp)"
  cp "${abs}" "${RUNTIME_CONFIG_BACKUP}"

  # `assetsBaseUrl` stays empty in both modes: app-owned assets are always
  # served next to the bundle, whether that is nginx or a desktop shell.
  cat >"${abs}" <<EOF
/**
 * Runtime configuration for Vendei Full — generated by ${script_name}.
 *
 * Rewritten on every run and restored on exit. This is the only supported way
 * to change deployment settings without rebuilding the bundle.
 *
 * Never put database credentials here: this file is served to every client.
 */
window.__VENDEI_CONFIG__ = {
  apiBaseUrl: '${api_base_url}',
  assetsBaseUrl: '',
  platform: '${platform}',
};
EOF
}

runtime_config_restore() {
  local root="$1"
  local abs="${root}/${RUNTIME_CONFIG_REL}"
  if [[ -n "${RUNTIME_CONFIG_BACKUP:-}" && -f "${RUNTIME_CONFIG_BACKUP:-}" ]]; then
    cp "${RUNTIME_CONFIG_BACKUP}" "${abs}"
    rm -f "${RUNTIME_CONFIG_BACKUP}"
    RUNTIME_CONFIG_BACKUP=""
    echo "restored ${RUNTIME_CONFIG_REL}"
  fi
}

# ── Foreground child supervision ─────────────────────────────────────────
# Bash defers trap handlers until a foreground child exits, so a long-running
# `npm start` would otherwise swallow Ctrl-C's cleanup: the trap never runs, and
# runtime-config.js is left rewritten. Running the child in the background and
# `wait`ing on it lets signals be handled immediately.
#
# `npm start` spawns the real server as a grandchild, so killing the PID we
# captured is not enough — the port is reclaimed as well.
#
# $1: child pid, $2: script name, $3: port the child listens on
stop_frontend() {
  local frontend_pid="$1"
  local script_name="$2"
  local port="$3"

  if [[ -n "${frontend_pid}" ]] && kill -0 "${frontend_pid}" 2>/dev/null; then
    echo "${script_name}: stopping frontend (PID ${frontend_pid})..."
    kill "${frontend_pid}" 2>/dev/null || true
    wait "${frontend_pid}" 2>/dev/null || true
  fi
  free_listen_port "${port}" "frontend"
}

# ── Backend supervision ─────────────────────────────────────────────────
# `run-inventory-backend.sh` execs `npm start`, which spawns node as a
# *grandchild*. Killing the script's PID therefore leaves the API listening on
# its port, so the next run trips over it and a stale backend can serve the
# wrong database. Reclaiming the port is the reliable stop.
#
# $1: backend wrapper pid, $2: script name, $3: port the backend listens on
stop_backend() {
  local backend_pid="$1"
  local script_name="$2"
  local port="$3"

  if [[ -n "${backend_pid}" ]] && kill -0 "${backend_pid}" 2>/dev/null; then
    echo "${script_name}: stopping backend (PID ${backend_pid})..."
    kill "${backend_pid}" 2>/dev/null || true
    wait "${backend_pid}" 2>/dev/null || true
  fi
  free_listen_port "${port}" "inventory backend"
}

# ── Database bootstrap ───────────────────────────────────────────────────
# Shared FULL_STACK_DB handling so every start script agrees on what
# "default" means. Reads migrate/seed from stdout as "1" or "0".
resolve_db_steps() {
  local script_name="$1"

  if [[ -n "${FULL_STACK_DB:-}" ]]; then
    case "${FULL_STACK_DB}" in
      both|all)
        echo "1 1"
        ;;
      migrate|migrations)
        echo "1 0"
        ;;
      seed|seeds)
        echo "0 1"
        ;;
      none|off|skip)
        echo "0 0"
        ;;
      *)
        echo "${script_name}: invalid FULL_STACK_DB=${FULL_STACK_DB} (use both|migrate|seed|none)" >&2
        exit 1
        ;;
    esac
    return
  fi

  local migrate=1
  local seed=1
  [[ "${FULL_STACK_SKIP_MIGRATE:-}" == "1" ]] && migrate=0
  [[ "${FULL_STACK_SKIP_SEED:-}" == "1" ]] && seed=0
  echo "${migrate} ${seed}"
}

run_db_steps() {
  local backend_dir="$1"
  local run_migrate="$2"
  local run_seed="$3"
  local script_name="$4"

  if [[ "${run_migrate}" == "1" ]]; then
    echo "${script_name}: db:migrate in ${backend_dir}..."
    (cd "${backend_dir}" && npm run db:migrate)
  else
    echo "${script_name}: skipping db:migrate"
  fi

  if [[ "${run_seed}" == "1" ]]; then
    echo "${script_name}: db:seed in ${backend_dir}..."
    (cd "${backend_dir}" && npm run db:seed)
  else
    echo "${script_name}: skipping db:seed"
  fi
}
