#!/usr/bin/env node
/**
 * Run a subset of the unit suite in isolation.
 *
 *   node scripts/test-scoped.mjs app/core
 *   node scripts/test-scoped.mjs app/services/vendei
 *   node scripts/test-scoped.mjs spec:pos-sale
 *
 * Why this exists: the full suite is ~747 specs and intermittently aborts
 * part-way through with a browser disconnect, without any pattern to where it
 * stops (see docs/architecture/baseline-test-failures.txt). Being able to take
 * one folder to completion is what makes a change verifiable before commit.
 *
 * How it works: the karma builder in this repo
 * (`@angular-devkit/build-angular:karma`) rejects `--include` and `--tsConfig`,
 * and filtering the `webpackContext` keys in `src/test.ts` does not help — that
 * context module evaluates every matching spec when it is required, regardless
 * of which keys are iterated. So this generates a throwaway entry file with
 * static imports of just the matching specs, registers it in the spec tsconfig
 * `files` list (the builder does not add `--main` to the program itself), and
 * points `ng test --main` at it. Everything is restored afterwards.
 */
import { readFileSync, readdirSync, statSync, writeFileSync, rmSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative, resolve, sep } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = resolve(ROOT, 'src');
const ENTRY = resolve(SRC, 'test.scoped.generated.ts');
const ENTRY_REL = 'test.scoped.generated.ts';
const TSCONFIG = resolve(SRC, 'tsconfig.spec.json');
const originalTsconfig = readFileSync(TSCONFIG, 'utf8');

const target = process.argv[2];
if (!target) {
  console.error('usage: node scripts/test-scoped.mjs <path-substring>\n  e.g. node scripts/test-scoped.mjs app/core');
  process.exit(2);
}

function findSpecs(dir, acc = []) {
  for (const entry of readdirSync(dir)) {
    if (entry === 'node_modules') continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      findSpecs(full, acc);
    } else if (entry.endsWith('.spec.ts')) {
      acc.push(full);
    }
  }
  return acc;
}

const specName = target.startsWith('spec:') ? target.slice('spec:'.length) : null;
const matched = specName
  ? findSpecs(SRC).filter((f) => f.endsWith(`${specName}.spec.ts`))
  : findSpecs(resolve(SRC, target)).filter((f) => f.startsWith(resolve(SRC, target)));

if (!matched.length) {
  const scope = specName ? `spec name "${specName}"` : `directory ${resolve(SRC, target)}`;
  console.error(`[test-scoped] no spec files found for ${scope}`);
  process.exit(2);
}

let status = 1;
try {
  const imports = matched
    .map((f) => `import './${relative(SRC, f).split(sep).join('/')}';`)
    .sort()
    .join('\n');

  writeFileSync(
    ENTRY,
    [
      '// Generated by scripts/test-scoped.mjs — do not edit, do not commit.',
      "import './test.setup';",
      '',
      imports,
      '',
    ].join('\n')
  );

  const patchedTsconfig = originalTsconfig.replace(
    /"files"\s*:\s*\[[\s\S]*?\]/,
    // `test.ts` is deliberately dropped here: it holds the webpackContext that
    // loads every spec in the repo, which is exactly what a scoped run avoids.
    `"files": ["${ENTRY_REL}", "polyfills.ts"]`
  );
  if (patchedTsconfig === originalTsconfig) {
    throw new Error('could not register the scoped entry in src/tsconfig.spec.json');
  }
  // The builder also treats every `*.spec.ts` matched by the tsconfig `include`
  // globs as an entry point, so those have to be narrowed too — otherwise a
  // "scoped" run silently executes the whole suite again.
  const specGlobs = matched
    .map((f) => `${relative(SRC, f).split(sep).join('/')}`)
    .sort()
    .join(',');
  const withInclude = patchedTsconfig.replace(
    /"include"\s*:\s*\[[\s\S]*?\]/,
    `"include": [${matched.map((f) => JSON.stringify(relative(SRC, f).split(sep).join('/'))).join(', ')}]`
  );
  if (withInclude === patchedTsconfig) {
    throw new Error('could not narrow the include globs in src/tsconfig.spec.json');
  }
  writeFileSync(TSCONFIG, withInclude);

  console.log(`[test-scoped] ${matched.length} spec file(s) matched "${target}"`);
  const result = spawnSync(
    'npx',
    [
      'ng',
      'test',
      '--watch=false',
      '--browsers=ChromeHeadlessNoSandbox',
      '--main=src/test.scoped.generated.ts',
      // The builder discovers spec files by globbing the project source root,
      // not from the tsconfig, so it has to be narrowed explicitly too.
      `--include=${specGlobs}`,
    ],
    { cwd: ROOT, stdio: 'inherit' }
  );
  status = result.status ?? 1;
} catch (err) {
  console.error(err);
} finally {
  rmSync(ENTRY, { force: true });
  writeFileSync(TSCONFIG, originalTsconfig);
}

process.exit(status);
