import 'zone.js/testing';

import { getTestBed } from '@angular/core/testing';
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';

/**
 * Test environment bootstrap, shared by the full entry (`test.ts`) and the
 * scoped entry generated by `scripts/test-scoped.mjs`.
 *
 * Kept separate from `test.ts` so a scoped run can initialise Angular without
 * also pulling in the `webpackContext` that loads every spec in the repo.
 */
getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());
