import { AngQuestion } from './ang-models';

export const SEED_QUESTIONS: Omit<AngQuestion, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // ===== BASIC (1-35) =====
  {
    text: 'What is a component in Angular?',
    complexity: 'basic',
    explanation: 'A component is a class with a template that controls a part of the UI.',
    options: [
      { text: 'A class that controls a view via a template', correct: true },
      { text: 'A module that imports other modules', correct: false },
      { text: 'A service that provides data', correct: false },
      { text: 'A directive that modifies the DOM', correct: false },
    ],
  },
  {
    text: 'Which decorator is used to define a component?',
    complexity: 'basic',
    explanation: '@Component decorator provides metadata like selector, template, and styles.',
    options: [
      { text: '@Component', correct: true },
      { text: '@Directive', correct: false },
      { text: '@NgModule', correct: false },
      { text: '@Injectable', correct: false },
    ],
  },
  {
    text: 'What is the purpose of the ngOnInit lifecycle hook?',
    complexity: 'basic',
    explanation: 'ngOnInit is called once after the component is initialized and input properties are set.',
    options: [
      { text: 'To initialize input properties', correct: false },
      { text: 'To perform initialization logic after component construction', correct: true },
      { text: 'To clean up resources before component destruction', correct: false },
      { text: 'To detect changes in the component', correct: false },
    ],
  },
  {
    text: 'Which syntax is used for property binding in Angular?',
    complexity: 'basic',
    explanation: 'Square brackets [property] bind a value from the component class to the DOM.',
    options: [
      { text: '[property]="value"', correct: true },
      { text: "{{ property }}", correct: false },
      { text: "(property)='value'", correct: false },
      { text: "#property='value'", correct: false },
    ],
  },
  {
    text: 'How do you listen to a DOM event in Angular?',
    complexity: 'basic',
    explanation: 'Parentheses (event) bind event handlers to DOM events.',
    options: [
      { text: '[click]="handler()"', correct: false },
      { text: '(click)="handler()"', correct: true },
      { text: '{{click}}="handler()"', correct: false },
      { text: '*click="handler()"', correct: false },
    ],
  },
  {
    text: 'What is string interpolation in Angular?',
    complexity: 'basic',
    explanation: 'Double curly braces {{ }} evaluate an expression and insert the result as text.',
    options: [
      { text: 'A way to bind events using parenthesis', correct: false },
      { text: 'A way to embed expressions into HTML using {{ }}', correct: true },
      { text: 'A directive for conditionally rendering elements', correct: false },
      { text: 'A method for looping over arrays', correct: false },
    ],
  },
  {
    text: 'What does NgFor directive do?',
    complexity: 'basic',
    explanation: 'NgFor (now @for) iterates over a collection and renders a template for each item.',
    options: [
      { text: 'Repeats a template for each item in a collection', correct: true },
      { text: 'Conditionally shows or hides an element', correct: false },
      { text: 'Applies CSS classes conditionally', correct: false },
      { text: 'Creates a new component instance', correct: false },
    ],
  },
  {
    text: 'What does NgIf directive do?',
    complexity: 'basic',
    explanation: 'NgIf (now @if) conditionally includes or removes elements from the DOM.',
    options: [
      { text: 'Conditionally renders an element', correct: true },
      { text: 'Loops over a collection', correct: false },
      { text: 'Adds CSS classes based on an expression', correct: false },
      { text: 'Creates a form control', correct: false },
    ],
  },
  {
    text: 'What is a module in Angular?',
    complexity: 'basic',
    explanation: 'An NgModule is a container for related components, directives, pipes, and services.',
    options: [
      { text: 'A container that organizes related parts of the application', correct: true },
      { text: 'A class that handles HTTP requests', correct: false },
      { text: 'A template for routing configuration', correct: false },
      { text: 'A service for dependency injection', correct: false },
    ],
  },
  {
    text: 'What is the purpose of the selector in @Component?',
    complexity: 'basic',
    explanation: 'The selector defines the custom HTML tag that represents the component in templates.',
    options: [
      { text: 'It defines the custom HTML tag used to embed the component', correct: true },
      { text: 'It selects DOM elements to apply directives', correct: false },
      { text: 'It selects which styles to apply', correct: false },
      { text: 'It selects the route path for the component', correct: false },
    ],
  },
  {
    text: 'What is the difference between constructor and ngOnInit?',
    complexity: 'basic',
    explanation: 'Constructor is called first for class initialization; ngOnInit is called after inputs are set.',
    options: [
      { text: 'They are the same thing', correct: false },
      { text: 'Constructor is called before ngOnInit, and inputs are available in ngOnInit', correct: true },
      { text: 'ngOnInit is called before the constructor', correct: false },
      { text: 'Constructor is only called once, ngOnInit runs on every change detection', correct: false },
    ],
  },
  {
    text: 'How do you pass data from a parent component to a child?',
    complexity: 'basic',
    explanation: 'Use @Input decorator in the child component to receive data from the parent.',
    options: [
      { text: 'Using @Input decorator', correct: true },
      { text: 'Using @Output decorator', correct: false },
      { text: 'Using EventEmitter', correct: false },
      { text: 'Using ViewChild', correct: false },
    ],
  },
  {
    text: 'How do you emit events from a child to a parent?',
    complexity: 'basic',
    explanation: 'Use @Output with an EventEmitter to emit events from child to parent.',
    options: [
      { text: 'Using @Input decorator', correct: false },
      { text: 'Using @Output with EventEmitter', correct: true },
      { text: 'By directly calling a parent method', correct: false },
      { text: 'Using a service', correct: false },
    ],
  },
  {
    text: 'What is two-way binding syntax in Angular?',
    complexity: 'basic',
    explanation: '[(ngModel)] combines property binding and event binding for two-way data flow.',
    options: [
      { text: '[()] or [(ngModel)]', correct: true },
      { text: '{{ }}', correct: false },
      { text: '()', correct: false },
      { text: '[]', correct: false },
    ],
  },
  {
    text: 'What CLI command creates a new component?',
    complexity: 'basic',
    explanation: 'ng generate component component-name (or ng g c) creates a new component.',
    options: [
      { text: 'ng new component', correct: false },
      { text: 'ng generate component', correct: true },
      { text: 'ng create component', correct: false },
      { text: 'ng add component', correct: false },
    ],
  },
  {
    text: 'What is the Angular CLI?',
    complexity: 'basic',
    explanation: 'The Angular CLI is a command-line tool for initializing, developing, and maintaining Angular apps.',
    options: [
      { text: 'A command-line interface for Angular development', correct: true },
      { text: 'A code editor for Angular', correct: false },
      { text: 'A testing framework for Angular', correct: false },
      { text: 'A package manager for Angular libraries', correct: false },
    ],
  },
  {
    text: 'What is a template in Angular?',
    complexity: 'basic',
    explanation: 'A template is an HTML snippet that tells Angular how to render the component.',
    options: [
      { text: 'A reusable HTML snippet with Angular bindings and directives', correct: true },
      { text: 'A CSS stylesheet for styling components', correct: false },
      { text: 'A TypeScript class that holds data', correct: false },
      { text: 'A configuration file for routing', correct: false },
    ],
  },
  {
    text: 'What is the purpose of angular.json?',
    complexity: 'basic',
    explanation: 'angular.json contains workspace-wide configuration for the Angular CLI.',
    options: [
      { text: 'It contains CLI configuration for the Angular workspace', correct: true },
      { text: 'It manages package dependencies', correct: false },
      { text: 'It stores environment variables', correct: false },
      { text: 'It defines TypeScript compiler options', correct: false },
    ],
  },
  {
    text: 'What does the async pipe do?',
    complexity: 'basic',
    explanation: 'The async pipe subscribes to an Observable or Promise and returns the latest value.',
    options: [
      { text: 'It subscribes to an Observable and returns the latest value', correct: true },
      { text: 'It creates an Observable from a value', correct: false },
      { text: 'It converts a Promise into an Observable', correct: false },
      { text: 'It delays the rendering of a component', correct: false },
    ],
  },
  {
    text: 'What is a pipe in Angular?',
    complexity: 'basic',
    explanation: 'A pipe transforms data in templates, like date formatting or text transformation.',
    options: [
      { text: 'A function that transforms data in templates', correct: true },
      { text: 'A way to pass data between components', correct: false },
      { text: 'A method for handling HTTP requests', correct: false },
      { text: 'A routing guard', correct: false },
    ],
  },
  {
    text: 'What does the date pipe do?',
    complexity: 'basic',
    explanation: 'The date pipe formats a date value according to locale rules.',
    options: [
      { text: 'It formats a date value', correct: true },
      { text: 'It creates a new Date object', correct: false },
      { text: 'It calculates the difference between two dates', correct: false },
      { text: 'It converts a string to a Date', correct: false },
    ],
  },
  {
    text: 'What is a directive in Angular?',
    complexity: 'basic',
    explanation: 'A directive is a class that modifies the appearance or behavior of DOM elements.',
    options: [
      { text: 'A class that modifies the DOM', correct: true },
      { text: 'A module that exports components', correct: false },
      { text: 'A service that handles HTTP', correct: false },
      { text: 'A template for routing', correct: false },
    ],
  },
  {
    text: 'What is the difference between component and directive?',
    complexity: 'basic',
    explanation: 'A component is a directive with a template; directives (structural/attribute) have no template.',
    options: [
      { text: 'A component has a template, a directive does not', correct: true },
      { text: 'A directive has a template, a component does not', correct: false },
      { text: 'They are exactly the same', correct: false },
      { text: 'Components cannot use lifecycle hooks', correct: false },
    ],
  },
  {
    text: 'What is a structural directive?',
    complexity: 'basic',
    explanation: 'Structural directives (like *ngIf, *ngFor) change the DOM layout by adding/removing elements.',
    options: [
      { text: 'A directive that changes the DOM structure', correct: true },
      { text: 'A directive that changes element appearance', correct: false },
      { text: 'A directive that handles events', correct: false },
      { text: 'A directive that formats data', correct: false },
    ],
  },
  {
    text: 'What is an attribute directive?',
    complexity: 'basic',
    explanation: 'Attribute directives (like NgClass, NgStyle) change the appearance or behavior of elements.',
    options: [
      { text: 'A directive that changes element appearance or behavior', correct: true },
      { text: 'A directive that adds/removes DOM elements', correct: false },
      { text: 'A directive that handles routing', correct: false },
      { text: 'A directive that creates components', correct: false },
    ],
  },
  {
    text: 'What does NgClass do?',
    complexity: 'basic',
    explanation: 'NgClass dynamically adds or removes CSS classes based on an expression.',
    options: [
      { text: 'Dynamically adds or removes CSS classes', correct: true },
      { text: 'Creates new CSS classes', correct: false },
      { text: 'Replaces all CSS classes on an element', correct: false },
      { text: 'Generates inline styles', correct: false },
    ],
  },
  {
    text: 'What is the safe navigation operator (?.)?',
    complexity: 'basic',
    explanation: 'The ?. operator prevents errors when accessing properties of null or undefined objects.',
    options: [
      { text: 'It prevents null/undefined errors when accessing nested properties', correct: true },
      { text: 'It navigates to a route safely', correct: false },
      { text: 'It ensures a value is not empty', correct: false },
      { text: 'It validates form inputs', correct: false },
    ],
  },
  {
    text: 'What command creates a new Angular project?',
    complexity: 'basic',
    explanation: 'ng new project-name scaffolds a new Angular workspace with initial app.',
    options: [
      { text: 'ng new project-name', correct: true },
      { text: 'ng create project-name', correct: false },
      { text: 'ng init project-name', correct: false },
      { text: 'ng start project-name', correct: false },
    ],
  },
  {
    text: 'What is the default port for Angular dev server?',
    complexity: 'basic',
    explanation: 'The Angular dev server runs on port 4200 by default.',
    options: [
      { text: '4200', correct: true },
      { text: '3000', correct: false },
      { text: '8080', correct: false },
      { text: '5000', correct: false },
    ],
  },
  {
    text: 'What is the purpose of the styleUrls property in @Component?',
    complexity: 'basic',
    explanation: 'styleUrls specifies the CSS files to apply to the component template.',
    options: [
      { text: 'It lists CSS files for the component', correct: true },
      { text: 'It defines inline styles for the component', correct: false },
      { text: 'It imports global styles', correct: false },
      { text: 'It generates style classes automatically', correct: false },
    ],
  },
  {
    text: 'What is NgSwitch?',
    complexity: 'basic',
    explanation: 'NgSwitch is a structural directive that conditionally renders one element from multiple choices.',
    options: [
      { text: 'A directive for conditional rendering with multiple cases', correct: true },
      { text: 'A directive for toggling between two views', correct: false },
      { text: 'A routing mechanism for switching pages', correct: false },
      { text: 'A method for swapping component states', correct: false },
    ],
  },
  {
    text: 'What type of files make up an Angular component?',
    complexity: 'basic',
    explanation: 'A component typically has a TS class, HTML template, and optionally CSS styles and spec test.',
    options: [
      { text: 'TypeScript, HTML, CSS (and spec.ts for tests)', correct: true },
      { text: 'Only TypeScript', correct: false },
      { text: 'TypeScript and JSON', correct: false },
      { text: 'HTML and JavaScript only', correct: false },
    ],
  },
  {
    text: 'What is the root module of an Angular app usually called?',
    complexity: 'basic',
    explanation: 'The root module is conventionally named AppModule and is defined in app.module.ts.',
    options: [
      { text: 'AppModule', correct: true },
      { text: 'RootModule', correct: false },
      { text: 'MainModule', correct: false },
      { text: 'CoreModule', correct: false },
    ],
  },
  {
    text: 'What is the purpose of the providers array in NgModule?',
    complexity: 'basic',
    explanation: 'The providers array registers services with the Angular dependency injection system.',
    options: [
      { text: 'It registers services for dependency injection', correct: true },
      { text: 'It declares components used in the module', correct: false },
      { text: 'It imports other modules', correct: false },
      { text: 'It defines the bootstrap component', correct: false },
    ],
  },
  {
    text: 'What CLI command serves the application?',
    complexity: 'basic',
    explanation: 'ng serve builds and serves the app, watching for file changes.',
    options: [
      { text: 'ng serve', correct: true },
      { text: 'ng run', correct: false },
      { text: 'ng start', correct: false },
      { text: 'ng build', correct: false },
    ],
  },

  // ===== INTERMEDIATE (36-70) =====
  {
    text: 'What is a service in Angular?',
    complexity: 'intermediate',
    explanation: 'A service is a class with focused functionality, injected via DI for reusability.',
    options: [
      { text: 'A class that provides reusable functionality across components', correct: true },
      { text: 'A component that handles HTTP requests', correct: false },
      { text: 'A module that imports HTTP features', correct: false },
      { text: 'A directive that modifies service behavior', correct: false },
    ],
  },
  {
    text: 'How is dependency injection configured in Angular?',
    complexity: 'intermediate',
    explanation: 'Services are registered via the providers array in NgModule, component, or @Injectable providedIn.',
    options: [
      { text: 'Using the providers array or @Injectable({ providedIn: "root" })', correct: true },
      { text: 'By directly instantiating services in components', correct: false },
      { text: 'Using a separate configuration file', correct: false },
      { text: 'By declaring services in the declarations array', correct: false },
    ],
  },
  {
    text: 'What is providedIn: "root" in @Injectable?',
    complexity: 'intermediate',
    explanation: 'providedIn: "root" makes the service a singleton available app-wide without adding it to providers.',
    options: [
      { text: 'It registers the service as an app-wide singleton', correct: true },
      { text: 'It limits the service to the root component only', correct: false },
      { text: 'It creates a new instance per component', correct: false },
      { text: 'It provides the service from a lazy-loaded root', correct: false },
    ],
  },
  {
    text: 'What is the difference between providedIn: "root" and providedIn: "any"?',
    complexity: 'intermediate',
    explanation: '"root" creates a single app-wide instance; "any" creates a new instance per lazy-loaded module.',
    options: [
      { text: '"root" is singleton; "any" creates new instance per lazy module', correct: true },
      { text: '"root" is for root components only; "any" is for any component', correct: false },
      { text: 'There is no difference', correct: false },
      { text: '"any" is deprecated', correct: false },
    ],
  },
  {
    text: 'What is the RouterModule.forRoot() method used for?',
    complexity: 'intermediate',
    explanation: 'forRoot() configures the root-level router with routes and returns a module with providers.',
    options: [
      { text: 'Configures the root router with application routes', correct: true },
      { text: 'Configures routing for feature modules', correct: false },
      { text: 'Creates a new router instance', correct: false },
      { text: 'Registers route guards', correct: false },
    ],
  },
  {
    text: 'What is the difference between forRoot() and forChild()?',
    complexity: 'intermediate',
    explanation: 'forRoot() is for the root module with provider setup; forChild() for feature modules without providers.',
    options: [
      { text: 'forRoot() sets up providers; forChild() does not create new router service instances', correct: true },
      { text: 'forChild() is for root and forRoot() for children', correct: false },
      { text: 'There is no difference', correct: false },
      { text: 'forRoot() is deprecated', correct: false },
    ],
  },
  {
    text: 'How do you define a route parameter in Angular?',
    complexity: 'intermediate',
    explanation: 'A colon prefix like :id in the route path defines a route parameter.',
    options: [
      { text: 'Using a colon prefix in the path, e.g., /users/:id', correct: true },
      { text: 'Using a query string like /users?id=123', correct: false },
      { text: 'Using a matrix parameter', correct: false },
      { text: 'Using route data property', correct: false },
    ],
  },
  {
    text: 'How do you access route parameters in a component?',
    complexity: 'intermediate',
    explanation: 'Inject ActivatedRoute and use paramMap observable or snapshot.paramMap.',
    options: [
      { text: 'Using ActivatedRoute.paramMap or snapshot.paramMap', correct: true },
      { text: 'Using Router.params', correct: false },
      { text: 'Using Route.params directly', correct: false },
      { text: 'Using NgRouteParams service', correct: false },
    ],
  },
  {
    text: 'What is a route guard in Angular?',
    complexity: 'intermediate',
    explanation: 'Route guards control navigation access (CanActivate, CanDeactivate, etc.).',
    options: [
      { text: 'An interface that controls access to routes', correct: true },
      { text: 'A middleware that logs route changes', correct: false },
      { text: 'A component that displays page not found', correct: false },
      { text: 'A service that pre-fetches route data', correct: false },
    ],
  },
  {
    text: 'Which route guards exist in Angular?',
    complexity: 'intermediate',
    explanation: 'CanActivate, CanActivateChild, CanDeactivate, CanLoad, and Resolve.',
    options: [
      { text: 'CanActivate, CanDeactivate, CanLoad, Resolve, CanActivateChild', correct: true },
      { text: 'CanActivate, CanDeactivate, CanMatch', correct: false },
      { text: 'Only CanActivate', correct: false },
      { text: 'CanActivate, CanDeactivate, PreloadGuard', correct: false },
    ],
  },
  {
    text: 'What is lazy loading in Angular?',
    complexity: 'intermediate',
    explanation: 'Lazy loading loads feature modules on demand, reducing initial bundle size.',
    options: [
      { text: 'Loading modules on demand to improve performance', correct: true },
      { text: 'Loading all modules at application startup', correct: false },
      { text: 'A technique for deferring image loading', correct: false },
      { text: 'Postponing HTTP requests until needed', correct: false },
    ],
  },
  {
    text: 'What syntax enables lazy loading in Angular routes?',
    complexity: 'intermediate',
    explanation: 'loadChildren: () => import() dynamically imports the feature module.',
    options: [
      { text: 'loadChildren: () => import("./module").then(m => m.Module)', correct: true },
      { text: 'lazyLoad: true', correct: false },
      { text: 'component: () => import("./component")', correct: false },
      { text: 'children: [] with lazy flag', correct: false },
    ],
  },
  {
    text: 'What is the purpose of the HttpClient in Angular?',
    complexity: 'intermediate',
    explanation: 'HttpClient provides a simplified API for HTTP communication with typed responses.',
    options: [
      { text: 'It performs HTTP requests with typed responses', correct: true },
      { text: 'It manages client-side caching', correct: false },
      { text: 'It provides WebSocket connections', correct: false },
      { text: 'It handles form validation', correct: false },
    ],
  },
  {
    text: 'How do you handle HTTP errors in Angular?',
    complexity: 'intermediate',
    explanation: 'Use catchError operator from RxJS in the pipe, or subscribe error callback.',
    options: [
      { text: 'Using catchError operator in pipe or subscribe error callback', correct: true },
      { text: 'Using try/catch blocks', correct: false },
      { text: 'Using onError lifecycle hook', correct: false },
      { text: 'Errors are handled automatically', correct: false },
    ],
  },
  {
    text: 'What are HTTP interceptors in Angular?',
    complexity: 'intermediate',
    explanation: 'Interceptors are middleware that can modify or log HTTP requests and responses globally.',
    options: [
      { text: 'Middleware that intercepts and transforms HTTP requests/responses', correct: true },
      { text: 'Components that display HTTP errors', correct: false },
      { text: 'Route guards for HTTP endpoints', correct: false },
      { text: 'Services that cache HTTP responses', correct: false },
    ],
  },
  {
    text: 'What is a FormControl in Angular?',
    complexity: 'intermediate',
    explanation: 'FormControl tracks the value and validation state of an individual form input.',
    options: [
      { text: 'It tracks value and validation of a single form input', correct: true },
      { text: 'It groups multiple form controls', correct: false },
      { text: 'It represents an entire form', correct: false },
      { text: 'It submits form data to a server', correct: false },
    ],
  },
  {
    text: 'What is the difference between Template-driven and Reactive forms?',
    complexity: 'intermediate',
    explanation: 'Template-driven forms use directives in HTML; Reactive forms use FormGroups/FormControls in code.',
    options: [
      { text: 'Reactive forms use FormGroups in code; template-driven use directives in HTML', correct: true },
      { text: 'Template-driven forms are more scalable', correct: false },
      { text: 'Reactive forms cannot be validated', correct: false },
      { text: 'There is no difference', correct: false },
    ],
  },
  {
    text: 'What is FormBuilder?',
    complexity: 'intermediate',
    explanation: 'FormBuilder is a service that provides syntactic sugar for creating FormGroups and FormControls.',
    options: [
      { text: 'A service for creating forms with less boilerplate', correct: true },
      { text: 'A directive that builds forms automatically', correct: false },
      { text: 'A component for rendering form fields', correct: false },
      { text: 'A validator for form inputs', correct: false },
    ],
  },
  {
    text: 'How do you add validation to a Reactive Form?',
    complexity: 'intermediate',
    explanation: 'Add Validators as the second argument when creating FormControl or FormGroup controls.',
    options: [
      { text: 'By passing Validators to FormControl or FormGroup', correct: true },
      { text: 'By adding required attributes in HTML', correct: false },
      { text: 'By using a ValidationService', correct: false },
      { text: 'Validation is automatic in Reactive Forms', correct: false },
    ],
  },
  {
    text: 'What is FormArray in Angular?',
    complexity: 'intermediate',
    explanation: 'FormArray manages a collection of FormControls or FormGroups as an array.',
    options: [
      { text: 'A way to manage a dynamic collection of form controls', correct: true },
      { text: 'A two-dimensional form layout', correct: false },
      { text: 'An array of form validators', correct: false },
      { text: 'A method for submitting multiple forms', correct: false },
    ],
  },
  {
    text: 'What is a custom pipe in Angular?',
    complexity: 'intermediate',
    explanation: 'A custom pipe is created with @Pipe decorator implementing PipeTransform interface.',
    options: [
      { text: 'A class decorated with @Pipe that implements PipeTransform', correct: true },
      { text: 'A special component for formatting data', correct: false },
      { text: 'A function in the template', correct: false },
      { text: 'A built-in Angular feature for all data transformations', correct: false },
    ],
  },
  {
    text: 'What is the pure property in @Pipe?',
    complexity: 'intermediate',
    explanation: 'A pure pipe only re-evaluates when its input changes; impure runs on every change detection.',
    options: [
      { text: 'Pure pipes re-evaluate only when input changes; impure on every CD cycle', correct: true },
      { text: 'Pure pipes are faster because they use memoization', correct: false },
      { text: 'Pure pipes always re-evaluate', correct: false },
      { text: 'The pure property is deprecated', correct: false },
    ],
  },
  {
    text: 'What is a ViewChild?',
    complexity: 'intermediate',
    explanation: 'ViewChild queries a child component, directive, or DOM element from the component view.',
    options: [
      { text: 'A decorator that queries a child element from the view', correct: true },
      { text: 'A decorator that queries content projected children', correct: false },
      { text: 'A directive for accessing parent components', correct: false },
      { text: 'A service for managing child routes', correct: false },
    ],
  },
  {
    text: 'What is the difference between ViewChild and ContentChild?',
    complexity: 'intermediate',
    explanation: 'ViewChild queries elements in the component template; ContentChild queries projected content.',
    options: [
      { text: 'ViewChild queries template; ContentChild queries projected (ng-content) content', correct: true },
      { text: 'ViewChild queries projected content; ContentChild queries template', correct: false },
      { text: 'They are identical', correct: false },
      { text: 'ViewChild is for elements, ContentChild is for components only', correct: false },
    ],
  },
  {
    text: 'What is the purpose of ng-content?',
    complexity: 'intermediate',
    explanation: 'ng-content creates a content projection slot for injecting content from a parent component.',
    options: [
      { text: 'It creates a projection point for parent content', correct: true },
      { text: 'It embeds child components', correct: false },
      { text: 'It loads content dynamically', correct: false },
      { text: 'It generates HTML content', correct: false },
    ],
  },
  {
    text: 'What is a Resolver in Angular routing?',
    complexity: 'intermediate',
    explanation: 'A Resolver pre-fetches data before navigating to a route, ensuring data is available.',
    options: [
      { text: 'It pre-fetches data before route activation', correct: true },
      { text: 'It resolves URL conflicts', correct: false },
      { text: 'It compiles templates at runtime', correct: false },
      { text: 'It resolves dependency injection conflicts', correct: false },
    ],
  },
  {
    text: 'What is the Angular Router event system?',
    complexity: 'intermediate',
    explanation: 'Router emits events (NavigationStart, NavigationEnd, etc.) that can be observed via Router.events.',
    options: [
      { text: 'Router.events emits lifecycle events like NavigationStart, NavigationEnd', correct: true },
      { text: 'A service for dispatching custom navigation events', correct: false },
      { text: 'A directive for handling router link clicks', correct: false },
      { text: 'A method for preventing navigation', correct: false },
    ],
  },
  {
    text: 'How do you style a component with scoped styles?',
    complexity: 'intermediate',
    explanation: 'Angular emulates Shadow DOM via view encapsulation; styles in the component only affect its template.',
    options: [
      { text: 'Styles in @Component styleUrls are scoped by default', correct: true },
      { text: 'Use <style scoped> in the template', correct: false },
      { text: 'Import a CSS file with :host selector', correct: false },
      { text: 'Scoped styles require ShadowDom encapsulation', correct: false },
    ],
  },
  {
    text: 'What are Angular lifecycle hooks in order?',
    complexity: 'intermediate',
    explanation: 'ngOnChanges, ngOnInit, ngDoCheck, ngAfterContentInit, ngAfterContentChecked, ngAfterViewInit, ngAfterViewChecked, ngOnDestroy.',
    options: [
      { text: 'ngOnChanges, ngOnInit, ngDoCheck, ngAfterContentInit, ngAfterViewInit, ngOnDestroy', correct: true },
      { text: 'ngOnInit, ngOnChanges, ngDoCheck, ngOnDestroy', correct: false },
      { text: 'ngOnInit, ngOnDestroy, ngAfterViewInit', correct: false },
      { text: 'ngAfterViewInit, ngOnChanges, ngOnInit, ngOnDestroy', correct: false },
    ],
  },
  {
    text: 'What is ngDoCheck used for?',
    complexity: 'intermediate',
    explanation: 'ngDoCheck is called on every change detection cycle, useful for detecting changes Angular misses.',
    options: [
      { text: 'It detects and acts upon changes Angular doesnt detect automatically', correct: true },
      { text: 'It checks form validity', correct: false },
      { text: 'It verifies component inputs', correct: false },
      { text: 'It validates route parameters', correct: false },
    ],
  },
  {
    text: 'What is ChangeDetectionStrategy.OnPush?',
    complexity: 'intermediate',
    explanation: 'OnPush tells Angular to run change detection only when inputs change or events fire.',
    options: [
      { text: 'A strategy that runs CD only when inputs change or events occur', correct: true },
      { text: 'The default change detection strategy', correct: false },
      { text: 'A strategy that disables change detection', correct: false },
      { text: 'A strategy that runs CD on every timer tick', correct: false },
    ],
  },
  {
    text: 'What is the trackBy function in NgFor used for?',
    complexity: 'intermediate',
    explanation: 'trackBy provides a unique identifier for each item, optimizing re-rendering by minimizing DOM changes.',
    options: [
      { text: 'It optimizes list rendering by identifying unique items', correct: true },
      { text: 'It tracks the order of items in a list', correct: false },
      { text: 'It monitors user clicks on list items', correct: false },
      { text: 'It tracks loading state of list items', correct: false },
    ],
  },
  {
    text: 'What is the purpose of the @HostListener decorator?',
    complexity: 'intermediate',
    explanation: '@HostListener subscribes to events on the host element of a directive or component.',
    options: [
      { text: 'It listens to events on the host element', correct: true },
      { text: 'It listens to events on child elements', correct: false },
      { text: 'It listens to global window events', correct: false },
      { text: 'It creates custom events', correct: false },
    ],
  },
  {
    text: 'What is the @HostBinding decorator used for?',
    complexity: 'intermediate',
    explanation: '@HostBinding binds a directive property to a property/attribute of the host element.',
    options: [
      { text: 'It binds a class property to a host element property', correct: true },
      { text: 'It binds a host element to a child component', correct: false },
      { text: 'It creates a two-way binding on the host', correct: false },
      { text: 'It binds a service to the component', correct: false },
    ],
  },

  // ===== ADVANCED (71-100) =====
  {
    text: 'What is Angular Change Detection and how does it work?',
    complexity: 'advanced',
    explanation: 'Angular uses Zone.js to monkey-patch async APIs; when callbacks fire, it triggers change detection from root to leaves.',
    options: [
      { text: 'Zone.js patches async APIs, triggering tree traversal to check for changes', correct: true },
      { text: 'It uses polling to periodically check for changes', correct: false },
      { text: 'It compares virtual DOM like React', correct: false },
      { text: 'It uses Web Workers for change detection', correct: false },
    ],
  },
  {
    text: 'How do you detach and reattach change detection?',
    complexity: 'advanced',
    explanation: 'Use ChangeDetectorRef.detach() to stop checking, reattach() to resume, or detectChanges() to manually check.',
    options: [
      { text: 'Using ChangeDetectorRef.detach(), reattach(), detectChanges()', correct: true },
      { text: 'Using ApplicationRef.detach()', correct: false },
      { text: 'By setting changeDetection: ChangeDetectionStrategy.Manual', correct: false },
      { text: 'Using NgZone.runOutsideAngular()', correct: false },
    ],
  },
  {
    text: 'What is the role of Zone.js in Angular?',
    complexity: 'advanced',
    explanation: 'Zone.js intercepts async operations and notifies Angular to run change detection when they complete.',
    options: [
      { text: 'It intercepts async operations to trigger change detection', correct: true },
      { text: 'It creates isolated execution zones for security', correct: false },
      { text: 'It manages memory allocation for Angular', correct: false },
      { text: 'It compiles Angular templates', correct: false },
    ],
  },
  {
    text: 'What is NgZone.runOutsideAngular used for?',
    complexity: 'advanced',
    explanation: 'It runs code outside the Angular zone, preventing change detection from being triggered by that code.',
    options: [
      { text: 'It runs code outside the Angular zone to avoid triggering CD', correct: true },
      { text: 'It runs code in a sandboxed environment', correct: false },
      { text: 'It executes code after Angular zone stabilizes', correct: false },
      { text: 'It destroys the current Angular zone', correct: false },
    ],
  },
  {
    text: 'How does Angular Ivy differ from the View Engine?',
    complexity: 'advanced',
    explanation: 'Ivy compiles to smaller bundles, offers incremental compilation, improved type checking, and better debugging.',
    options: [
      { text: 'Ivy offers smaller bundles, incremental compilation, improved type checking', correct: true },
      { text: 'Ivy uses a virtual DOM approach', correct: false },
      { text: 'Ivy is the same as View Engine with a different name', correct: false },
      { text: 'Ivy disables AOT compilation', correct: false },
    ],
  },
  {
    text: 'What is Angular Elements?',
    complexity: 'advanced',
    explanation: 'Angular Elements allows packaging Angular components as custom elements (Web Components).',
    options: [
      { text: 'A feature that packages Angular components as Web Components', correct: true },
      { text: 'A library of pre-built Angular components', correct: false },
      { text: 'A framework for building Angular UI components', correct: false },
      { text: 'A testing utility for Angular components', correct: false },
    ],
  },
  {
    text: 'What is the purpose of Angulars Dependency Injection hierarchy?',
    complexity: 'advanced',
    explanation: 'Angular DI has a hierarchy (module, component) where injectors create child injectors, allowing scoped service instances.',
    options: [
      { text: 'It creates child injectors, allowing scoped service instances per component/module', correct: true },
      { text: 'It flattens all services into a single injector', correct: false },
      { text: 'It prevents circular dependencies', correct: false },
      { text: 'It logs all dependency resolutions', correct: false },
    ],
  },
  {
    text: 'What are multi providers in Angular?',
    complexity: 'advanced',
    explanation: 'Multi providers allow multiple providers for the same DI token, used for HTTP interceptors and guards.',
    options: [
      { text: 'Multiple providers for the same token, merged into an array', correct: true },
      { text: 'Providers that inject multiple dependencies', correct: false },
      { text: 'A way to provide multiple instances of the same service', correct: false },
      { text: 'Providers that work with multiple modules', correct: false },
    ],
  },
  {
    text: 'What is a custom DI token in Angular?',
    complexity: 'advanced',
    explanation: 'Use InjectionToken to create custom DI tokens for non-class dependencies like objects or config.',
    options: [
      { text: 'An InjectionToken used as a DI key, often for non-class dependencies', correct: true },
      { text: 'A special provider for Angular services only', correct: false },
      { text: 'A token for Angular routing', correct: false },
      { text: 'An authentication token for HTTP requests', correct: false },
    ],
  },
  {
    text: 'What is the @Self decorator in DI?',
    complexity: 'advanced',
    explanation: '@Self restricts dependency resolution to the current injector only, skipping parent injectors.',
    options: [
      { text: 'It resolves a dependency only from the current injector', correct: true },
      { text: 'It resolves from the root injector', correct: false },
      { text: 'It creates a new service instance', correct: false },
      { text: 'It resolves from child injectors only', correct: false },
    ],
  },
  {
    text: 'What is the @SkipSelf decorator?',
    complexity: 'advanced',
    explanation: '@SkipSelf starts dependency resolution from the parent injector, skipping the current one.',
    options: [
      { text: 'It skips the current injector and resolves from the parent', correct: true },
      { text: 'It skips all injectors and creates a new instance', correct: false },
      { text: 'It skips the root injector', correct: false },
      { text: 'It skips optional dependencies', correct: false },
    ],
  },
  {
    text: 'What is the @Optional decorator?',
    complexity: 'advanced',
    explanation: '@Optional marks a dependency as optional; if not found, null is injected instead of throwing.',
    options: [
      { text: 'It makes a dependency optional, injecting null if unavailable', correct: true },
      { text: 'It provides a default value for dependencies', correct: false },
      { text: 'It makes the component optional in routing', correct: false },
      { text: 'It skips null checks on dependencies', correct: false },
    ],
  },
  {
    text: 'How do you create a custom structural directive?',
    complexity: 'advanced',
    explanation: 'Create a directive with a selector prefixed with *, inject TemplateRef and ViewContainerRef, and use createEmbeddedView.',
    options: [
      { text: 'Use TemplateRef, ViewContainerRef, and createEmbeddedView with a * selector', correct: true },
      { text: 'Use @Directive with a selector in square brackets', correct: false },
      { text: 'Extend the NgIf class', correct: false },
      { text: 'Use the @Structural decorator', correct: false },
    ],
  },
  {
    text: 'What is a microsyntax in Angular?',
    complexity: 'advanced',
    explanation: 'Microsyntax is the compact expression language used by structural directives like *ngIf and *ngFor.',
    options: [
      { text: 'The compact syntax used by structural directives like *ngFor', correct: true },
      { text: 'A syntax for defining microservices', correct: false },
      { text: 'The syntax for Angular animations', correct: false },
      { text: 'A template syntax for inline styles', correct: false },
    ],
  },
  {
    text: 'How does Angular handle tree-shaking?',
    complexity: 'advanced',
    explanation: 'Angular CLI uses Webpack/Rollup for tree-shaking; Ivy compiles to smaller code that better supports dead code elimination.',
    options: [
      { text: 'Ivy generates smaller, tree-shakeable code that Webpack/Rollup can eliminate', correct: true },
      { text: 'Angular manually removes unused code at build time', correct: false },
      { text: 'Angular uses a custom bundler', correct: false },
      { text: 'Tree-shaking is not supported in Angular', correct: false },
    ],
  },
  {
    text: 'What is the purpose of Angulars TestBed?',
    complexity: 'advanced',
    explanation: 'TestBed configures and creates Angular testing modules for unit testing components, services, and pipes.',
    options: [
      { text: 'It configures testing modules for component/service unit tests', correct: true },
      { text: 'It is an end-to-end testing framework', correct: false },
      { text: 'It tests HTTP endpoints', correct: false },
      { text: 'It validates Angular project structure', correct: false },
    ],
  },
  {
    text: 'What is the difference between TestBed.get and TestBed.inject?',
    complexity: 'advanced',
    explanation: 'TestBed.inject is the modern typed method; TestBed.get is deprecated in Angular 9+.',
    options: [
      { text: 'TestBed.inject is the typed replacement for deprecated TestBed.get', correct: true },
      { text: 'TestBed.get returns Observables, TestBed.inject returns promises', correct: false },
      { text: 'TestBed.get is for services, TestBed.inject is for components', correct: false },
      { text: 'There is no difference', correct: false },
    ],
  },
  {
    text: 'What is async/await vs fakeAsync in Angular testing?',
    complexity: 'advanced',
    explanation: 'fakeAsync allows controlling async operations synchronously with tick(); async flushes pending microtasks.',
    options: [
      { text: 'fakeAsync controls time with tick(); async waits for async operations to complete', correct: true },
      { text: 'fakeAsync is for Promises only; async is for Observables', correct: false },
      { text: 'They are interchangeable', correct: false },
      { text: 'async is deprecated in favor of fakeAsync', correct: false },
    ],
  },
  {
    text: 'What is the purpose of the tick() function in Angular tests?',
    complexity: 'advanced',
    explanation: 'tick() simulates the passage of time in fakeAsync zone, flushing pending async tasks.',
    options: [
      { text: 'It simulates time passage and flushes async tasks in fakeAsync', correct: true },
      { text: 'It ticks the Angular change detection cycle', correct: false },
      { text: 'It creates a timer for delayed execution', correct: false },
      { text: 'It records test execution time', correct: false },
    ],
  },
  {
    text: 'What is the purpose of the discardPeriodicTasks function?',
    complexity: 'advanced',
    explanation: 'discardPeriodicTasks clears any pending periodic timers (setInterval) in fakeAsync tests.',
    options: [
      { text: 'It clears pending setInterval timers in fakeAsync zone', correct: true },
      { text: 'It discards all pending HTTP requests', correct: false },
      { text: 'It removes unused test files', correct: false },
      { text: 'It cancels all Observables in a test', correct: false },
    ],
  },
  {
    text: 'What is the purpose of Angular Schematics?',
    complexity: 'advanced',
    explanation: 'Schematics are code generators that can create, modify, or refactor Angular project files.',
    options: [
      { text: 'Code generators that create and modify Angular project files', correct: true },
      { text: 'A visual schema designer for databases', correct: false },
      { text: 'A tool for generating Angular documentation', correct: false },
      { text: 'A testing framework for Angular schemas', correct: false },
    ],
  },
  {
    text: 'What is the Angular compiler?',
    complexity: 'advanced',
    explanation: 'The Angular compiler transforms templates and decorators into executable JavaScript code, supporting JIT and AOT modes.',
    options: [
      { text: 'It transforms Angular templates and decorators into JavaScript', correct: true },
      { text: 'It compiles TypeScript to JavaScript only', correct: false },
      { text: 'It is the same as the TypeScript compiler', correct: false },
      { text: 'It compiles SCSS to CSS', correct: false },
    ],
  },
  {
    text: 'What is the difference between JIT and AOT compilation?',
    complexity: 'advanced',
    explanation: 'JIT compiles in the browser at runtime; AOT compiles during build for faster rendering and smaller bundles.',
    options: [
      { text: 'JIT compiles in browser at runtime; AOT compiles at build time', correct: true },
      { text: 'JIT is faster at runtime; AOT is slower', correct: false },
      { text: 'AOT compiles in the browser; JIT compiles during build', correct: false },
      { text: 'There is no difference', correct: false },
    ],
  },
  {
    text: 'How do you optimize an Angular application for production?',
    complexity: 'advanced',
    explanation: 'Use AOT, enable production mode, lazy load modules, use OnPush CD, minimize bundle with CLI optimizations, enable PWA.',
    options: [
      { text: 'AOT, production mode, lazy loading, OnPush CD, CLI optimizations', correct: true },
      { text: 'Disable change detection entirely', correct: false },
      { text: 'Use only inline templates', correct: false },
      { text: 'Avoid using services', correct: false },
    ],
  },
  {
    text: 'What is the Angular PreloadingStrategy?',
    complexity: 'advanced',
    explanation: 'PreloadingStrategy decides how and when to preload lazy-loaded modules in the background.',
    options: [
      { text: 'A strategy that controls background loading of lazy modules', correct: true },
      { text: 'A strategy for preloading images', correct: false },
      { text: 'A method for caching API responses', correct: false },
      { text: 'A way to pre-compile templates', correct: false },
    ],
  },
  {
    text: 'What is the difference between PreloadAllModules and QuicklinkStrategy?',
    complexity: 'advanced',
    explanation: 'PreloadAllModules loads all lazy modules after bootstrap; QuicklinkStrategy preloads based on viewport visibility.',
    options: [
      { text: 'PreloadAllModules loads all; QuicklinkStrategy loads based on viewport visibility', correct: true },
      { text: 'PreloadAllModules is faster than QuicklinkStrategy', correct: false },
      { text: 'QuicklinkStrategy loads all modules immediately', correct: false },
      { text: 'They are identical', correct: false },
    ],
  },
  {
    text: 'How do you create a shared module in Angular?',
    complexity: 'advanced',
    explanation: 'Create an NgModule that exports common components, directives, pipes, and modules used across features.',
    options: [
      { text: 'Create an NgModule that declares and exports shared items for reuse', correct: true },
      { text: 'Add all components to the AppModule', correct: false },
      { text: 'Use a global services module', correct: false },
      { text: 'Create a separate app for shared components', correct: false },
    ],
  },
  {
    text: 'What is the purpose of the forwardRef function?',
    complexity: 'advanced',
    explanation: 'forwardRef allows referencing a class that is not yet defined, resolving circular dependency issues.',
    options: [
      { text: 'It references a class defined later, resolving circular dependencies', correct: true },
      { text: 'It forwards a value to a child component', correct: false },
      { text: 'It creates a reference to a forward route', correct: false },
      { text: 'It pre-renders component content', correct: false },
    ],
  },
  {
    text: 'What is the Angular runtime performance profiler?',
    complexity: 'advanced',
    explanation: 'Angular DevTools provides a profiler for change detection cycles, component tree, and performance bottlenecks.',
    options: [
      { text: 'Angular DevTools profiler shows CD cycles and performance data', correct: true },
      { text: 'A built-in CLI command for profiling', correct: false },
      { text: 'Chrome DevTools Performance tab integrated with Angular', correct: false },
      { text: 'There is no profiler for Angular', correct: false },
    ],
  },
  {
    text: 'What is Internationalization (i18n) in Angular?',
    complexity: 'advanced',
    explanation: 'Angular i18n uses decorators like i18n for templates, and @angular/localize for translating text.',
    options: [
      { text: 'A built-in system for translating app text and locale formatting', correct: true },
      { text: 'An external library for language translation', correct: false },
      { text: 'A way to internationalize dates only', correct: false },
      { text: 'A method for global CSS styling', correct: false },
    ],
  },
  {
    text: 'What is the Service Worker in Angular PWA?',
    complexity: 'advanced',
    explanation: 'Angular Service Worker (@angular/service-worker) enables offline support, caching, and background sync for PWAs.',
    options: [
      { text: 'It enables offline support, caching, and background sync for PWAs', correct: true },
      { text: 'It manages Angular dependency injection', correct: false },
      { text: 'It handles server-side rendering', correct: false },
      { text: 'It processes background HTTP requests', correct: false },
    ],
  },
];
